dummy_products = [ 
  {
    "name": "AirPods Pro",
    "image": "/images/airpods.jpg",
    "description": "AirPods Pro have been designed to deliver Active Noise Cancellation for immersive sound, Transparency mode so you can hear your surroundings, and a customizable fit for all-day comfort. Just like AirPods, AirPods Pro connect magically to your iPhone or Apple Watch. And they’re ready to use right out of the case.",
    "brand": "Apple",
    "category": "Electronics",
    "price": 249.99,
    "count_in_stock": 3,
    "rating": 0,
    "num_reviews": 0,
    "owner_id":"1"
  },
  {
    "name": "Echo Dot (4th Gen)",
    "image": "/images/echo-dot.jpg",
    "description": "Meet the all-new Echo Dot - Our most popular smart speaker with Alexa. The sleek, compact design delivers crisp vocals and balanced bass for full sound.",
    "brand": "Amazon",
    "category": "Electronics",
    "price": 49.99,
    "count_in_stock": 23,
    "rating": 0,
    "num_reviews": 0,
    "owner_id":"1"
  },
  {
    "name": "Macbook Air 2020",
    "image": "/images/macbook-air.jpg",
    "description": "Our thinnest, lightest notebook, completely transformed by the Apple M1 chip. CPU speeds up to 3.5x faster. GPU speeds up to 5x faster. Our most advanced Neural Engine for up to 9x faster machine learning. The longest battery life ever in a MacBook Air. And a silent, fanless design. This much power has never been this ready to go.",
    "brand": "Apple",
    "category": "Electronics",
    "price": 999.99,
    "count_in_stock": 13,
    "rating": 0,
    "num_reviews": 0,
    "owner_id":"1"
  },
  {
    "name": "Nokia 7.2",
    "image": "/images/nokia7.jpg",
    "description": "The Nokia 7.2 Edge embodies the best of form and function – packing incredible performance into a beautifully sleek frame and Lightning-fast 64 bit, Octa-core processor.",
    "brand": "Nokia",
    "category": "Electronics",
    "price": 199.99,
    "count_in_stock": 33,
    "rating": 0,
    "num_reviews": 0,
    "owner_id":"1"
  },
  {
    "name": "Acer Nitro 5",
    "image": "/images/acer-nitro.jpg",
    "description": "Soar to new gaming heights—anytime, anywhere—with the Nitro 5. This ultra-cool machine is sure to catch your eye with its sleek, mobile design, 15.6” Full HD IPS Display, and a wide range of gaming-rich features to put you in total command of the action. Leveraging the power and speed of its 9th Gen Intel Core processor and high-performance NVIDIA GeForce GTX 1650 graphics—that’s driven by NVIDIA Turing architecture.",
    "brand": "Acer",
    "category": "Electronics",
    "price": 649.99,
    "count_in_stock": 3,
    "rating": 0,
    "num_reviews": 0,
    "owner_id":"1"
  },
  {
    "name": "New Apple MacBook Pro (16-inch)",
    "image": "/images/macbook-pro.jpg",
    "description": "Our thinnest, lightest notebook, completely transformed by the Apple M1 chip. CPU speeds up to 3.5x faster. GPU speeds up to 5x faster. Our most advanced Neural Engine for up to 9x faster machine learning. The longest battery life ever in a MacBook Air. And a silent, fanless design. This much power has never been this ready to go.",
    "brand": "Apple",
    "category": "Electronics",
    "price": 2449.99,
    "count_in_stock": 0,
    "rating": 0,
    "num_reviews": 0,
    "owner_id":1
  },

  {
    "name": "Sony (DSCW800) Digital Camera (Silver)",
    "image": "/images/sony.jpg",
    "description": "This incredibly easy-to-use camera slips right in your pocket, ready to capture a memory at a moment's notice. Get close to faraway subjects with 5x optical zoom, then snap gorgeous 20.1 MP photos or record beautifully detailed HD video. Your pictures will come out crisp and clear thanks to the professional-grade Sony lens with Optical SteadyShot image stabilization. For even more fun, enhance your stills and video with built-in creative effects like toy camera and pop color.",
    "brand": "Apple",
    "category": "Electronics",
    "price": 112.99,
    "count_in_stock": 3,
    "rating": 0,
    "num_reviews": 0,
    "owner_id":"1"
  },
  {
    "name": "Sony Headphone",
    "image": "/images/sony-headphone.jpg",
    "description": "Maximizing your personal audio experience has never been easier than with SONY ZX-Series Monitor headphones. Built with comfort and performance in mind, there’s no need to compromise.",
    "brand": "Sony",
    "category": "Electronics",
    "price": 199.99,
    "count_in_stock": 33,
    "rating": 0,
    "num_reviews": 0,
    "owner_id":"1"
  },
  {
    "name": "Beats Solo3",
    "image": "/images/beats.jpg",
    "description": "The Beats Solo3 Edge embodies the best of form and function – packing incredible performance into a beautifully sleek frame and Lightning-fast 64 bit, Octa-core processor.",
    "brand": "Beats",
    "category": "Electronics",
    "price": 199.99,
    "count_in_stock": 33,
    "rating": 0,
    "num_reviews": 0,
    "owner_id":"1"
  },
  {
    "name": "Samsung Galaxy S6",
    "image": "/images/samsung-s6.jpg",
    "description": "The Samsung Galaxy S6 Edge embodies the best of form and function – packing incredible performance into a beautifully sleek frame and Lightning-fast 64 bit, Octa-core processor.",
    "brand": "Samsung",
    "category": "Electronics",
    "price": 199.99,
    "count_in_stock": 33,
    "rating": 0,
    "num_reviews": 0,
    "owner_id":"1"
  },
];
