version: "3.3"

services:
  server:
    build: .
    ports:
      - "5000:5000"
  #   depends_on:
  #     - "db"

  # db:
  #   image: "postgres"
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_USER: "postgres"
  #     POSTGRES_PASSWORD: "password"
  #     POSTGRES_DATABASE: "postgres"
