apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
      - ./infra/k8s-dev/*
build:
  local:
    push: false
  artifacts:
    - image: apahadi73/auth-go
      context: authentication
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.go"
            dest: .
    - image: apahadi73/products
      context: products
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.py"
            dest: .
    - image: apahadi73/butik-client
      context: client
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "**/*.js"
            dest: .
    - image: apahadi73/butik-cart
      context: cart
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.kt"
            dest: .
    # - image: apahadi/orders
    #   context: orders
    #   docker:
    #     dockerfile: Dockerfile
    #   sync:
    #     manual:
    #       - src: "src/**/*.ts"
    #         dest: .
    # - image: apahadi/expiration
    #   context: expiration
    #   docker:
    #     dockerfile: Dockerfile
    #   sync:
    #     manual:
    #       - src: "src/**/*.ts"
    #         dest: .
    # - image: apahadi/payments
    #   context: payments
    #   docker:
    #     dockerfile: Dockerfile
    #   sync:
    #     manual:
    #       - src: "src/**/*.ts"
    #         dest: .
