version: "3.3"

services:
  db:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DATABASE: "postgres"

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  # auth:
  #   image: acim/go-reflex
  #   environment:
  #     - RACE_DETECTOR=1
  #     - BUILD_ARGS=./cmd/main.go
  #   volumes:
  #     - .:/app
  #   ports:
  #     - 3001:3001
  #   depends_on:
  #     - "db"
