version: "3.3"

services:
  db:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DATABASE: "postgres"

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  auth:
    image: apahadi73/auth-go
    ports:
      - 5000:5000
    depends_on:
      - "db"
    environment:
      - PORT:5000
      - HOST:"db"
