version: "3.3"

services:
  auth-postgres:
    image: "apahadi73/auth-postgres"
    ports:
      - "5430:5430"

  auth:
    image: apahadi73/auth-go
    # build: .
    ports:
      - 5000:5000
    depends_on:
      - "auth-postgres"
    environment:
      PORT: "5000"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DATABASE: "postgres"
      POSTGRES_PORT: "5430"
      ACCESS_SECRET: "aavash123"
      HOST: "auth-postgres"
