version: "3.3"

services:
  db:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DATABASE: "authentication_db"
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
