version: "3.3"

services:
  auth-mongo:
    image: mongo
    ports:
      - "27017:27017"

  # auth:
  #   build: .
  #   ports:
  #     - 5000:5000
  #   depends_on:
  #     - "auth-mongo"
  #   environment:
  #     PORT: "5000"
  #     JWT_KEY: "secret_key"
  #     MONGO_URI: mongodb://auth-mongo:27017/auth
