version: "3.3"

services:
  butik-cart:
    image: apahadi73/butik-cart
    ports:
      - 27020:27020

  # server:
  #   image: apahadi73/products
  #   ports:
  #     - 5000:5000
  #   depends_on:
  #     - "db"
  #   environment:
  #     POSTGRES_USER: "postgres"
  #     POSTGRES_PASSWORD: "password"
  #     POSTGRES_DATABASE: "postgres"
  #     POSTGRES_SERVER: "db"
  #     POSTGRES_PORT: "5432"
  #     POSTGRES_DB: "postgres"
