version: "3.9"

services:
  #  cart-mongod:
  #    image: apahadi73/cart-mongod
  #    ports:
  #      - "27020:27020"

  cart-server:
    build: .
    #    depends_on:
    #      - cart-mongod
    environment:
      - ENVIRONMENT=dev
    ports:
      - "5003:5003"
