apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: apahadi73/auth-go
          env:
            - name: HOST
              value: auth-postgres-srv
            - name: DATABASE_URL
              value: "postgresql://product:password@auth-postgres-srv:27018/auth"
            - name: SECRET_KEY
              value: "postgres"
            - name: POSTGRES_USER
              value: "product"
            - name: POSTGRES_PASSWORD
              value: "password"
            - name: POSTGRES_SERVER
              value: "db"
            - name: POSTGRES_PORT
              value: "27018"
            - name: POSTGRES_DB
              value: "auth"
            - name: PORT
              value: "auth"

---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 5000
      targetPort: 5000
