apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-postgres-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-postgres
  template:
    metadata:
      labels:
        app: auth-postgres
    spec:
      containers:
        - name: auth-postgres
          image: postgres
          env:
            - name: SECRET_KEY
              value: "postgres"
            - name: POSTGRES_USER
              value: "product"
            - name: POSTGRES_PASSWORD
              value: "password"
            - name: POSTGRES_SERVER
              value: "db"
            - name: POSTGRES_PORT
              value: "5431"
            - name: POSTGRES_DB
              value: "auth"
            - name: PORT
              value: "auth"

---
apiVersion: v1
kind: Service
metadata:
  name: auth-postgres-srv
spec:
  selector:
    app: auth-postgres
  ports:
    - name: db
      protocol: TCP
      port: 27018
      targetPort: 5431
