apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-mongod-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart-mongod
  template:
    metadata:
      labels:
        app: cart-mongod
    spec:
      containers:
        - name: cart-mongod
          image: apahadi73/cart-mongod
---
apiVersion: v1
kind: Service
metadata:
  name: cart-mongod-srv
spec:
  selector:
    app: cart-mongod
  ports:
    - name: proddb
      protocol: TCP
      port: 27020
      targetPort: 27020
