apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
        - name: products
          image: apahadi73/products
          env:
            - name: DATABASE_URL
              value: "postgresql://postgress:password@localhost:27017/products"
            - name: SECRET_KEY
              value: "postgres"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "password"
            - name: POSTGRES_SERVER
              value: "db"
            - name: POSTGRES_PORT
              value: "27017"
            - name: POSTGRES_DB
              value: "products"

---
apiVersion: v1
kind: Service
metadata:
  name: products-srv
spec:
  selector:
    app: products
  ports:
    - name: products
      protocol: TCP
      port: 5000
      targetPort: 5000
