apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-postgres-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products-postgres
  template:
    metadata:
      labels:
        app: products-postgres
    spec:
      containers:
        - name: products-postgres
          image: postgres
          env:
            - name: POSTGRES_USER
              value: "product"
            - name: POSTGRES_PASSWORD
              value: "password"
            - name: POSTGRES_SERVER
              value: "db"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: "products"

---
apiVersion: v1
kind: Service
metadata:
  name: products-postgres-srv
spec:
  selector:
    app: products-postgres
  ports:
    - name: db
      protocol: TCP
      port: 5432
      targetPort: 5432
