version: "3.3"

services:
  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DATABASE: "postgres"

  server:
    build: .
    ports:
      - 5000:5000
    depends_on:
      - "db"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DATABASE: "postgres"
      POSTGRES_SERVER: "db"
      POSTGRES_PORT: "5432"
      POSTGRES_DB: "postgres"
